In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("mov.csv")

In [5]:
df.head(5)
mov=df.copy()

In [6]:
mov

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [7]:
mov.shape

(1000, 16)

In [8]:
mov.describe()

       IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  843.000000  1.000000e+03
mean      7.949300   77.971530  2.736929e+05
std       0.275491   12.376099  3.273727e+05
min       7.600000   28.000000  2.508800e+04
25%       7.700000   70.000000  5.552625e+04
50%       7.900000   79.000000  1.385485e+05
75%       8.100000   87.000000  3.741612e+05
max       9.300000  100.000000  2.343110e+06

In [9]:
mov.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

mov.dtype

In [10]:
mov.dtypes

Poster_Link       object
Series_Title      object
Released_Year     object
Certificate       object
Runtime           object
Genre             object
IMDB_Rating      float64
Overview          object
Meta_score       float64
Director          object
Star1             object
Star2             object
Star3             object
Star4             object
No_of_Votes        int64
Gross             object
dtype: object

In [11]:
mov['No_of_Votes']

0      2343110
1      1620367
2      2303232
3      1129952
4       689845
        ...
995     166544
996      34075
997      43374
998      26471
999      51853
Name: No_of_Votes, Length: 1000, dtype: int64

In [12]:
mov['Gross']

0       28,341,469
1      134,966,411
2      534,858,444
3       57,300,000
4        4,360,000
          ...
995            NaN
996            NaN
997     30,500,000
998            NaN
999            NaN
Name: Gross, Length: 1000, dtype: object

In [13]:
mov.drop('Gross',axis=1)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853

In [14]:
mov.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [15]:
mov.drop(columns=['Poster_Link','Released_Year','Certificate','Runtime','IMDB_Rating','Meta_score','No_of_Votes'],inplace=True)

In [16]:
mov.columns

Index(['Series_Title', 'Genre', 'Overview', 'Director', 'Star1', 'Star2',
       'Star3', 'Star4', 'Gross'],
      dtype='object')

In [17]:
mov.dtypes

Series_Title    object
Genre           object
Overview        object
Director        object
Star1           object
Star2           object
Star3           object
Star4           object
Gross           object
dtype: object

In [18]:
mov.head()

,Series_Title,Genre,Overview,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,Drama,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,The Godfather,"Crime, Drama",An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
2,The Dark Knight,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,The Godfather: Part II,"Crime, Drama",The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
4,12 Angry Men,"Crime, Drama",A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"

In [19]:
mov.isna().sum()

Series_Title      0
Genre             0
Overview          0
Director          0
Star1             0
Star2             0
Star3             0
Star4             0
Gross           169
dtype: int64

mov.shape

In [20]:
mov.shape

(1000, 9)

In [21]:
mov.head()

,Series_Title,Genre,Overview,Director,Star1,Star2,Star3,Star4,Gross
0,The Shawshank Redemption,Drama,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469"
1,The Godfather,"Crime, Drama",An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411"
2,The Dark Knight,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444"
3,The Godfather: Part II,"Crime, Drama",The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000"
4,12 Angry Men,"Crime, Drama",A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000"

In [22]:
colm=mov.columns

In [23]:
colm

Index(['Series_Title', 'Genre', 'Overview', 'Director', 'Star1', 'Star2',
       'Star3', 'Star4', 'Gross'],
      dtype='object')

In [24]:
len(mov)

1000

for i in range(len(mov)):

In [25]:
mov['tags']=mov['Genre'] +" " +mov['Overview']+" "+ mov['Director'] +" " +mov['Star1'] +" "+mov['Star2']+" "+mov['Star3']+" "+mov['Star4']

In [26]:
mov['tags']

0      Drama Two imprisoned men bond over a number of...
1      Crime, Drama An organized crime dynasty's agin...
2      Action, Crime, Drama When the menace known as ...
3      Crime, Drama The early life and career of Vito...
4      Crime, Drama A jury holdout attempts to preven...
                             ...
995    Comedy, Drama, Romance A young New York social...
996    Drama, Western Sprawling epic covering the lif...
997    Drama, Romance, War In Hawaii in 1941, a priva...
998    Drama, War Several survivors of a torpedoed me...
999    Crime, Mystery, Thriller A man in London tries...
Name: tags, Length: 1000, dtype: object

mov

In [27]:
mov

,Series_Title,Genre,Overview,Director,Star1,Star2,Star3,Star4,Gross,tags
0,The Shawshank Redemption,Drama,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"28,341,469",Drama Two imprisoned men bond over a number of...
1,The Godfather,"Crime, Drama",An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"134,966,411","Crime, Drama An organized crime dynasty's agin..."
2,The Dark Knight,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"534,858,444","Action, Crime, Drama When the menace known as ..."
3,The Godfather: Part II,"Crime, Drama",The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"57,300,000","Crime, Drama The early life and career of Vito..."
4,12 Angry Men,"Crime, Drama",A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"4,360,000","Crime, Drama A jury holdout attempts to preven..."
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,"Comedy, Drama, Romance",A young New York socialite becomes interested ...,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,NaN,"Comedy, Drama, Romance A young New York social..."
996,Giant,"Drama, Western",Sprawling epic covering the life of a Texas ca...,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,NaN,"Drama, Western Sprawling epic covering the lif..."
997,From Here to Eternity,"Drama, Romance, War","In Hawaii in 1941, a private is cruelly punish...",Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,"30,500,000","Drama, Romance, War In Hawaii in 1941, a priva..."
998,Lifeboat,"Drama, War",Several survivors of a torpedoed merchant ship...,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,NaN,"Drama, War Several survivors of a torpedoed me..."
999,The 39 Steps,"Crime, Mystery, Thriller",A man in London tries to help a counter-espion...,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,NaN,"Crime, Mystery, Thriller A man in London tries..."

In [28]:
colm

Index(['Series_Title', 'Genre', 'Overview', 'Director', 'Star1', 'Star2',
       'Star3', 'Star4', 'Gross'],
      dtype='object')

In [29]:
list(colm)

['Series_Title',
 'Genre',
 'Overview',
 'Director',
 'Star1',
 'Star2',
 'Star3',
 'Star4',
 'Gross']

In [30]:
colm=list(colm)

In [31]:
colm

['Series_Title',
 'Genre',
 'Overview',
 'Director',
 'Star1',
 'Star2',
 'Star3',
 'Star4',
 'Gross']

In [32]:
mov.drop(colm,axis=1,inplace=True)

In [33]:
mov['Title']=df['Series_Title']

In [34]:
mov['tags'][0]

'Drama Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. Frank Darabont Tim Robbins Morgan Freeman Bob Gunton William Sadler'

In [35]:
import nltk

In [36]:
from nltk.stem.porter import PorterStemmer
con=PorterStemmer()

In [37]:
def conver(wor):
    y=[]
    for i in wor.split():
        y.append(con.stem(i))
    stor=" ".join(y)
    return stor

In [38]:
conver("dacned")

'dacn'

In [39]:
#conver(mov['tags'])

In [40]:
mov['tags']=mov['tags'].apply(conver)

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
tex=CountVectorizer(max_features=450,stop_words='english')

In [42]:
arr=tex.fit_transform(mov['tags']).toarray()
arr

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [43]:
tex.get_feature_names_out()

array(['aamir', 'accus', 'act', 'action', 'adventur', 'adventure', 'age',
       'agent', 'agre', 'akira', 'al', 'alan', 'alfr', 'allen',
       'american', 'anderson', 'andrew', 'animation', 'ann', 'anthoni',
       'apart', 'armi', 'art', 'artist', 'assassin', 'attack', 'attempt',
       'away', 'bale', 'band', 'base', 'battl', 'beauti', 'becom',
       'befor', 'begin', 'ben', 'bergman', 'best', 'billi', 'biography',
       'black', 'bob', 'bond', 'boy', 'brad', 'brian', 'bring', 'british',
       'brother', 'bruce', 'brutal', 'cameron', 'captain', 'captur',
       'car', 'care', 'career', 'cari', 'carl', 'case', 'catherin',
       'chang', 'chaplin', 'charl', 'child', 'childhood', 'children',
       'chri', 'christian', 'christoph', 'citi', 'city', 'class', 'clint',
       'coen', 'come', 'comedi', 'comedy', 'commit', 'confront', 'cooper',
       'cop', 'corrupt', 'coupl', 'creat', 'crew', 'crime', 'crimin',
       'damon', 'daniel', 'danni', 'daughter', 'davi', 'david', 'day',
       'dead', 'dean', 'death', 'decid', 'defend', 'desper', 'destroy',
       'detect', 'dian', 'dicaprio', 'die', 'differ', 'disappear',
       'discov', 'don', 'dougla', 'drama', 'dream', 'drug', 'dure',
       'earli', 'earth', 'eastwood', 'edward', 'elizabeth', 'embark',
       'emma', 'encount', 'end', 'enemi', 'escap', 'ethan', 'evan',
       'event', 'evil', 'ex', 'execut', 'experi', 'face', 'fall',
       'famili', 'family', 'fantasi', 'fantasy', 'father', 'fellow',
       'femal', 'fi', 'fight', 'film', 'final', 'follow', 'forc', 'ford',
       'form', 'franc', 'franci', 'frank', 'free', 'freeman', 'french',
       'friend', 'friendship', 'futur', 'game', 'gang', 'gangster',
       'gari', 'gene', 'gener', 'georg', 'german', 'girl', 'goe', 'good',
       'grant', 'great', 'group', 'grow', 'guy', 'ha', 'hank', 'harri',
       'harrison', 'hawk', 'hayao', 'help', 'henri', 'hepburn', 'hi',
       'high', 'hire', 'histori', 'history', 'hitchcock', 'ho', 'hoffman',
       'hollywood', 'home', 'hope', 'horror', 'hous', 'howard', 'hugh',
       'human', 'hunt', 'hunter', 'husband', 'ian', 'ii', 'indian',
       'inspir', 'investig', 'involv', 'jack', 'jackson', 'jake', 'jame',
       'jason', 'jean', 'jeff', 'jennif', 'jewish', 'jim', 'joe', 'joel',
       'john', 'johnni', 'johnson', 'join', 'jon', 'jone', 'joseph',
       'josh', 'journey', 'jr', 'juli', 'kapoor', 'katharin', 'keaton',
       'ken', 'kevin', 'khan', 'kill', 'killer', 'kim', 'king', 'know',
       'kurosawa', 'land', 'laura', 'lawyer', 'lead', 'leader', 'learn',
       'leav', 'lee', 'leigh', 'leonardo', 'life', 'like', 'littl',
       'live', 'lo', 'local', 'long', 'look', 'lord', 'loui', 'love',
       'lover', 'magic', 'make', 'man', 'mari', 'mark', 'marri', 'martin',
       'matt', 'matthew', 'max', 'mean', 'meet', 'men', 'michael',
       'michel', 'miller', 'miss', 'mission', 'mitchel', 'miyazaki',
       'mob', 'moor', 'mother', 'movi', 'murder', 'murray', 'music',
       'mysteri', 'mystery', 'nation', 'nazi', 'new', 'night', 'niro',
       'noir', 'offic', 'old', 'older', 'onli', 'order', 'pacino',
       'parker', 'past', 'patrick', 'paul', 'peopl', 'person', 'peter',
       'philip', 'pierr', 'pitt', 'plan', 'planet', 'play', 'plot',
       'polic', 'power', 'prison', 'protect', 'pursu', 'quest', 'race',
       'rachel', 'ray', 'real', 'rebel', 'relationship', 'rescu', 'retir',
       'return', 'rich', 'richard', 'ring', 'rob', 'robert', 'roman',
       'romanc', 'ron', 'roy', 'run', 'russel', 'ruthless', 'ryan', 'sam',
       'save', 'school', 'sci', 'scorses', 'scott', 'sean', 'search',
       'secret', 'seek', 'sent', 'seri', 'set', 'seven', 'sever', 'shah',
       'singer', 'singh', 'sister', 'small', 'soldier', 'son', 'south',
       'space', 'spi', 'spielberg', 'spirit', 'sport', 'stanley', 'star',
       'start', 'steal', 'stephen', 'steve', 'steven', 'stewart', 'stop',
       'stori', 'street', 'struggl', 'student', 'success', 'surviv',
       'tale', 'tatsuya', 'taylor', 'teacher', 'team', 'teenag', 'tell',
       'themselv', 'thi', 'thoma', 'thriller', 'tim', 'time', 'togeth',
       'tom', 'toni', 'town', 'track', 'train', 'travel', 'tri', 'trip',
       'troubl', 'true', 'turn', 'unit', 'use', 'van', 'veteran',
       'villag', 'violent', 'visit', 'von', 'wa', 'walter', 'want', 'war',
       'washington', 'watson', 'way', 'wealthi', 'western', 'wife',
       'wilder', 'william', 'woman', 'women', 'wood', 'woodi', 'work',
       'worker', 'world', 'wright', 'wrong', 'year', 'york', 'young'],
      dtype=object)

In [44]:
from sklearn.metrics.pairwise import  cosine_similarity

In [45]:
cos=cosine_similarity(arr)

In [46]:
cos[0],arr

(array([1.        , 0.07856742, 0.10540926, 0.06189845, 0.11111111,
        0.17817416, 0.10050378, 0.08908708, 0.        , 0.10540926,
        0.08333333, 0.08333333, 0.11111111, 0.09622504, 0.        ,
        0.05407381, 0.08084521, 0.13608276, 0.10050378, 0.08908708,
        0.11111111, 0.10050378, 0.16666667, 0.        , 0.07647191,
        0.15713484, 0.0860663 , 0.15713484, 0.08908708, 0.        ,
        0.11785113, 0.10540926, 0.18490007, 0.08333333, 0.09622504,
        0.11111111, 0.10050378, 0.08333333, 0.19245009, 0.09245003,
        0.09622504, 0.        , 0.07647191, 0.09245003, 0.        ,
        0.09245003, 0.08333333, 0.        , 0.        , 0.        ,
        0.0860663 , 0.07856742, 0.07856742, 0.08908708, 0.11111111,
        0.10050378, 0.12598816, 0.10050378, 0.09245003, 0.08084521,
        0.        , 0.        , 0.08908708, 0.        , 0.08908708,
        0.07106691, 0.        , 0.11111111, 0.13608276, 0.        ,
        0.        , 0.16666667, 0.07856742, 0.10540926, 0.10050378,
        0.        , 0.10540926, 0.10540926, 0.        , 0.09245003,
        0.09622504, 0.        , 0.17817416, 0.07856742, 0.16169042,
        0.11785113, 0.09622504, 0.08333333, 0.05479966, 0.11785113,
        0.11785113, 0.07856742, 0.13608276, 0.06537205, 0.10540926,
        0.        , 0.        , 0.1490712 , 0.10540926, 0.20100756,
        0.08333333, 0.09622504, 0.18490007, 0.19245009, 0.0860663 ,
        0.08084521, 0.        , 0.09622504, 0.10540926, 0.07856742,
        0.1490712 , 0.08333333, 0.09622504, 0.11111111, 0.09622504,
        0.        , 0.08333333, 0.06804138, 0.        , 0.        ,
        0.        , 0.11111111, 0.12598816, 0.11785113, 0.11111111,
        0.        , 0.07856742, 0.08084521, 0.09622504, 0.17213259,
        0.13608276, 0.08333333, 0.09245003, 0.11111111, 0.09245003,
        0.11111111, 0.08908708, 0.12598816, 0.0860663 , 0.12598816,
        0.        , 0.0860663 , 0.09622504, 0.08084521, 0.07856742,
        0.        , 0.08908708, 0.06666667, 0.07106691, 0.08084521,
        0.11111111, 0.0860663 , 0.09245003, 0.08084521, 0.11111111,
        0.        , 0.08908708, 0.09622504, 0.        , 0.08908708,
        0.13608276, 0.        , 0.08908708, 0.12598816, 0.09245003,
        0.08908708, 0.        , 0.20412415, 0.        , 0.09622504,
        0.        , 0.        , 0.08084521, 0.16169042, 0.27216553,
        0.09245003, 0.17817416, 0.        , 0.        , 0.0745356 ,
        0.19245009, 0.08333333, 0.10540926, 0.        , 0.10540926,
        0.09245003, 0.19245009, 0.09245003, 0.12598816, 0.12598816,
        0.11111111, 0.19245009, 0.10050378, 0.08084521, 0.        ,
        0.13608276, 0.11111111, 0.10540926, 0.12598816, 0.11785113,
        0.11111111, 0.06537205, 0.08333333, 0.09245003, 0.12598816,
        0.        , 0.12598816, 0.08908708, 0.1490712 , 0.        ,
        0.09245003, 0.09245003, 0.0727393 , 0.        , 0.11785113,
        0.16169042, 0.11111111, 0.0745356 , 0.09622504, 0.07856742,
        0.        , 0.11111111, 0.09622504, 0.        , 0.0745356 ,
        0.08084521, 0.08908708, 0.19245009, 0.23570226, 0.06537205,
        0.        , 0.06666667, 0.0860663 , 0.11785113, 0.17817416,
        0.11111111, 0.09245003, 0.11111111, 0.10540926, 0.06804138,
        0.08333333, 0.10050378, 0.        , 0.1490712 , 0.13608276,
        0.        , 0.1490712 , 0.08908708, 0.18490007, 0.18490007,
        0.11111111, 0.        , 0.        , 0.2773501 , 0.10540926,
        0.13900961, 0.11785113, 0.23570226, 0.10540926, 0.08333333,
        0.10050378, 0.10540926, 0.        , 0.0860663 , 0.10050378,
        0.10050378, 0.16169042, 0.09245003, 0.08908708, 0.08908708,
        0.        , 0.        , 0.20100756, 0.13608276, 0.12598816,
        0.        , 0.08908708, 0.        , 0.07856742, 0.22222222,
        0.33333333, 0.11111111, 0.06299408, 0.11111111, 0.09245003,
        0.12598816, 0.10540926, 0.13608276, 0.11785113, 0.19245009,
        0.1490712 , 0.12598816, 0.16666667, 0.11111111, 0.        ,
        0.0745356 , 0.11785113, 0.09622504, 0.08084521, 0.10050378,
        0.19245009, 0.13608276, 0.13608276, 0.10540926, 0.17817416,
        0.11111111, 0.18490007, 0.09245003, 0.09622504, 0.        ,
        0.11785113, 0.22222222, 0.08908708, 0.20100756, 0.0860663 ,
        0.07856742, 0.10540926, 0.13608276, 0.        , 0.10050378,
        0.        , 0.        , 0.1490712 , 0.10050378, 0.16666667,
        0.        , 0.        , 0.10540926, 0.0860663 , 0.08333333,
        0.        , 0.11785113, 0.0727393 , 0.07647191, 0.11785113,
        0.25197632, 0.12598816, 0.        , 0.0860663 , 0.        ,
        0.09622504, 0.13608276, 0.08084521, 0.09622504, 0.11111111,
        0.11785113, 0.09245003, 0.10540926, 0.0860663 , 0.10050378,
        0.11111111, 0.0727393 , 0.11785113, 0.12598816, 0.11111111,
        0.1490712 , 0.10540926, 0.        , 0.12598816, 0.11111111,
        0.10540926, 0.12598816, 0.        , 0.10540926, 0.09622504,
        0.10540926, 0.        , 0.        , 0.15294382, 0.        ,
        0.11785113, 0.0695048 , 0.13608276, 0.10050378, 0.06537205,
        0.09245003, 0.        , 0.20100756, 0.        , 0.0860663 ,
        0.09622504, 0.13608276, 0.09245003, 0.09622504, 0.0860663 ,
        0.09245003, 0.        , 0.13608276, 0.10050378, 0.        ,
        0.        , 0.20412415, 0.10050378, 0.        , 0.        ,
        0.07106691, 0.        , 0.11785113, 0.10540926, 0.08084521,
        0.10050378, 0.        , 0.0860663 , 0.11111111, 0.12598816,
        0.        , 0.        , 0.10540926, 0.14213381, 0.09622504,
        0.        , 0.09622504, 0.09622504, 0.11785113, 0.        ,
        0.        , 0.10050378, 0.        , 0.08084521, 0.09245003,
        0.        , 0.10050378, 0.10050378, 0.10540926, 0.07856742,
        0.11785113, 0.        , 0.19245009, 0.10540926, 0.08908708,
        0.08333333, 0.11111111, 0.16666667, 0.1490712 , 0.21081851,
        0.12598816, 0.08084521, 0.0860663 , 0.10050378, 0.06804138,
        0.10050378, 0.09245003, 0.09622504, 0.12598816, 0.10050378,
        0.15294382, 0.11111111, 0.12598816, 0.19245009, 0.        ,
        0.17213259, 0.0727393 , 0.11111111, 0.09622504, 0.16169042,
        0.07647191, 0.        , 0.09245003, 0.        , 0.10050378,
        0.09245003, 0.10050378, 0.11785113, 0.09622504, 0.10050378,
        0.27216553, 0.1490712 , 0.0860663 , 0.10540926, 0.10050378,
        0.10050378, 0.07856742, 0.08333333, 0.        , 0.0860663 ,
        0.09245003, 0.12598816, 0.        , 0.09622504, 0.08084521,
        0.25197632, 0.09622504, 0.        , 0.1490712 , 0.07647191,
        0.12598816, 0.06415003, 0.12598816, 0.        , 0.10050378,
        0.08333333, 0.11785113, 0.16666667, 0.        , 0.0860663 ,
        0.07647191, 0.09245003, 0.0860663 , 0.09622504, 0.        ,
        0.07647191, 0.09245003, 0.        , 0.        , 0.19245009,
        0.26726124, 0.        , 0.        , 0.25197632, 0.0727393 ,
        0.        , 0.        , 0.13608276, 0.09622504, 0.09622504,
        0.10050378, 0.06666667, 0.07647191, 0.10050378, 0.13608276,
        0.08908708, 0.09622504, 0.        , 0.0860663 , 0.17213259,
        0.10050378, 0.0860663 , 0.0727393 , 0.0727393 , 0.10050378,
        0.        , 0.09245003, 0.        , 0.07106691, 0.23570226,
        0.        , 0.18490007, 0.11111111, 0.13608276, 0.        ,
        0.        , 0.11111111, 0.07647191, 0.09622504, 0.        ,
        0.0727393 , 0.10050378, 0.07647191, 0.23570226, 0.10540926,
        0.08908708, 0.0860663 , 0.08333333, 0.16169042, 0.11785113,
        0.0745356 , 0.        , 0.16169042, 0.09245003, 0.08333333,
        0.        , 0.10050378, 0.        , 0.09622504, 0.08333333,
        0.        , 0.        , 0.07856742, 0.        , 0.        ,
        0.09245003, 0.13608276, 0.10050378, 0.08333333, 0.21081851,
        0.09622504, 0.        , 0.10540926, 0.        , 0.09245003,
        0.23570226, 0.08084521, 0.        , 0.        , 0.09622504,
        0.08908708, 0.        , 0.11785113, 0.05555556, 0.09245003,
        0.10050378, 0.        , 0.16666667, 0.13333333, 0.12598816,
        0.09622504, 0.0745356 , 0.09245003, 0.09622504, 0.        ,
        0.09622504, 0.10540926, 0.10050378, 0.09245003, 0.        ,
        0.06804138, 0.07856742, 0.09622504, 0.        , 0.09245003,
        0.09245003, 0.09622504, 0.13608276, 0.11111111, 0.07647191,
        0.        , 0.08908708, 0.09622504, 0.09622504, 0.13608276,
        0.08084521, 0.11785113, 0.1490712 , 0.        , 0.0860663 ,
        0.11111111, 0.10540926, 0.10050378, 0.10050378, 0.10050378,
        0.1490712 , 0.08908708, 0.08908708, 0.        , 0.        ,
        0.07647191, 0.08908708, 0.08908708, 0.10540926, 0.07647191,
        0.09245003, 0.08908708, 0.08333333, 0.09622504, 0.0860663 ,
        0.        , 0.0860663 , 0.10540926, 0.        , 0.09245003,
        0.07856742, 0.        , 0.09622504, 0.11785113, 0.08908708,
        0.0745356 , 0.10540926, 0.13900961, 0.07647191, 0.10050378,
        0.09245003, 0.08084521, 0.22222222, 0.08084521, 0.07856742,
        0.10540926, 0.        , 0.10540926, 0.10050378, 0.08333333,
        0.09245003, 0.22222222, 0.10540926, 0.17817416, 0.10050378,
        0.        , 0.09622504, 0.        , 0.        , 0.        ,
        0.18490007, 0.        , 0.11785113, 0.11111111, 0.11111111,
        0.        , 0.11111111, 0.11785113, 0.        , 0.18490007,
        0.10540926, 0.        , 0.        , 0.09622504, 0.        ,
        0.10540926, 0.09245003, 0.26726124, 0.        , 0.08084521,
        0.        , 0.10540926, 0.        , 0.09622504, 0.        ,
        0.11785113, 0.13608276, 0.        , 0.13333333, 0.0860663 ,
        0.08908708, 0.        , 0.        , 0.07856742, 0.        ,
        0.        , 0.12598816, 0.        , 0.08333333, 0.10540926,
        0.12598816, 0.08084521, 0.        , 0.08908708, 0.09245003,
        0.        , 0.0745356 , 0.        , 0.13608276, 0.09622504,
        0.        , 0.11111111, 0.07856742, 0.11111111, 0.08908708,
        0.11111111, 0.08908708, 0.        , 0.08333333, 0.20100756,
        0.        , 0.06537205, 0.11111111, 0.        , 0.        ,
        0.10050378, 0.        , 0.17213259, 0.11111111, 0.        ,
        0.        , 0.08084521, 0.0745356 , 0.16666667, 0.10050378,
        0.        , 0.        , 0.19245009, 0.11785113, 0.10540926,
        0.12598816, 0.        , 0.0860663 , 0.07647191, 0.12598816,
        0.13608276, 0.09245003, 0.08333333, 0.15713484, 0.10050378,
        0.11111111, 0.        , 0.0860663 , 0.21081851, 0.17213259,
        0.11111111, 0.        , 0.        , 0.08908708, 0.07647191,
        0.22222222, 0.        , 0.17213259, 0.09245003, 0.19245009,
        0.11785113, 0.09245003, 0.11785113, 0.0860663 , 0.12598816,
        0.09622504, 0.07647191, 0.09622504, 0.0860663 , 0.06537205,
        0.        , 0.        , 0.08084521, 0.17817416, 0.        ,
        0.        , 0.17817416, 0.08908708, 0.22222222, 0.09245003,
        0.07856742, 0.0860663 , 0.        , 0.        , 0.10050378,
        0.10540926, 0.10050378, 0.08084521, 0.10050378, 0.16169042,
        0.10540926, 0.        , 0.18490007, 0.0860663 , 0.11111111,
        0.14547859, 0.08908708, 0.        , 0.11111111, 0.18490007,
        0.09622504, 0.07647191, 0.08084521, 0.09245003, 0.        ,
        0.11111111, 0.12598816, 0.08333333, 0.09622504, 0.08333333,
        0.        , 0.09622504, 0.08333333, 0.11785113, 0.08908708,
        0.        , 0.0860663 , 0.        , 0.        , 0.        ,
        0.11111111, 0.07856742, 0.09622504, 0.        , 0.16666667,
        0.09245003, 0.10050378, 0.20100756, 0.        , 0.        ,
        0.        , 0.        , 0.12598816, 0.09245003, 0.10540926,
        0.11111111, 0.11111111, 0.09245003, 0.11111111, 0.09622504,
        0.        , 0.10540926, 0.10050378, 0.08908708, 0.        ,
        0.16169042, 0.16169042, 0.09245003, 0.09245003, 0.1490712 ,
        0.        , 0.09622504, 0.22222222, 0.08908708, 0.09245003,
        0.12598816, 0.17817416, 0.10540926, 0.19245009, 0.07647191,
        0.09245003, 0.1490712 , 0.        , 0.09245003, 0.09245003,
        0.05986843, 0.0745356 , 0.10540926, 0.11111111, 0.11111111,
        0.07856742, 0.08333333, 0.08084521, 0.10540926, 0.        ,
        0.        , 0.0860663 , 0.        , 0.08908708, 0.0860663 ,
        0.12598816, 0.        , 0.08084521, 0.        , 0.08333333,
        0.07856742, 0.10050378, 0.        , 0.08084521, 0.        ,
        0.17817416, 0.10050378, 0.10540926, 0.09245003, 0.        ,
        0.        , 0.10050378, 0.19245009, 0.08908708, 0.1490712 ,
        0.09245003, 0.09245003, 0.        , 0.25197632, 0.0860663 ,
        0.11111111, 0.10540926, 0.        , 0.12171612, 0.12598816,
        0.18490007, 0.0860663 , 0.07856742, 0.11111111, 0.0860663 ,
        0.08908708, 0.08908708, 0.06537205, 0.11785113, 0.20100756,
        0.13608276, 0.10050378, 0.        , 0.        , 0.11111111,
        0.09622504, 0.        , 0.09622504, 0.06804138, 0.13608276,
        0.10540926, 0.        , 0.10540926, 0.2773501 , 0.09622504,
        0.08333333, 0.        , 0.08908708, 0.        , 0.15713484,
        0.08908708, 0.09622504, 0.12598816, 0.10050378, 0.        ,
        0.        , 0.10540926, 0.        , 0.        , 0.06666667,
        0.11111111, 0.        , 0.10540926, 0.08084521, 0.        ,
        0.0745356 , 0.07647191, 0.        , 0.        , 0.09622504,
        0.0695048 , 0.08333333, 0.09622504, 0.10050378, 0.09245003,
        0.13608276, 0.        , 0.        , 0.10540926, 0.        ,
        0.07856742, 0.10050378, 0.09622504, 0.17213259, 0.        ]),
 array([[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]))

In [47]:

def rec(movie):
    
    movie_ind=mov[mov['Title'] == movie].index[0]
    
    dsit=cos[movie_ind]
    
    #dsit=dsit.astype(np.int64).all()
    lis=sorted(list(enumerate(dsit)),reverse=True,key=lambda x:x[1])[1:6]
    for i in lis: 
        print(mov.iloc[i[0]].Title)

In [48]:

rec('Avengers: Infinity War')

Captain America: Civil War
Avengers: Endgame
The Avengers
Captain America: The Winter Soldier
Iron Man

In [49]:

import pickle

In [54]:
pickle.dump(mov.to_dict,open('movi.pkl','wb'))
import joblib

In [51]:
pickle.dump(mov,open('mosv.pkl','wb'))

In [56]:
pickle.dump(cos,open('cosi.pkl','wb'))